#!/bin/sh
set -euo pipefail
script_dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
source "${script_dir}"/common.sh

NAMESPACE="${NAMESPACE:-clusters}"
NAME="${NAME:-example}"

export NAMESPACE
export NAME

echo "Starting control plane operators"

"${script_dir}"/start-cpo &> "${log_dir}"/start-cpo.log &
"${script_dir}"/start-hcco &> "${log_dir}"/start-hcco.log &
