#!/bin/sh
set -euo pipefail
script_dir="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
log_dir="$HOME"/.hypershift
mkdir -p "$log_dir" 2>/dev/null

HYPERSHIFT_DIR=${HYPERSHIFT_DIR:-$script_dir/../..}
pidfile="${log_dir}/hcco.pid"
if [[ -f ${pidfile} ]]; then 
	echo "Stopping hosted cluster config operator"
	kill -9 $(cat "${pidfile}") || true
	rm "${pidfile}"
else
	echo "No pid file found for hosted cluster config operator"
	exit 1
fi
   

